### ISSUE TITLE
Remove generated files from the dist directory

### ISSUE THREAD

**Issue by gkapfham** [MaddyKapfhammer/ActionTraction#2]
Hi @MaddyKapfhammer I noticed that the `dist` directory contains generated files, like the wheel created by the `poetry build` command. These generated files should not be stored inside of the GitHub repository. Instead, you should setup a release mechanism that makes it possible to create a tagged release and then upload the project to PyPI. As a start, can you please remove the generated files from the repository?

**Comment by MaddyKapfhammer** [comment]
The generated files have been removed from the 'dist' directory. I will focus on using 'poetry run' for running ActionTraction for now and will open a new issue when approaching uploading the project to PyPI.
