### ISSUE TITLE
Remove commented out code from the repository if it is not needed

### ISSUE THREAD

**Issue by gkapfham** [MaddyKapfhammer/ActionTraction#3]
Hello @MaddyKapfhammer I noticed that there are some commented out Python functions and lines of code inside of the repository. Can you please remove any commented-out code that is not absolutely needed? If the repository contains less commented-out code it is easier for developers to navigate the existing source code. Thanks!

**Comment by MaddyKapfhammer** [comment]
Unnecessary commented code has been removed from the repository. Some commented code was kept, this will eventually be reintroduced into the source code once problems with graphical representation are resolved.
