### ISSUE TITLE
Does the .VSCodeCounter directory need to be in the repository?

### ISSUE THREAD

**Issue by gkapfham** [MaddyKapfhammer/ActionTraction#5]
Hello @MaddyKapfhammer, I noticed that there is a `.VSCodeCounter` directory inside of the repository. Does it need to be there? What does this directory do? If it is needed, then can you please document its use inside of the `README` file? Otherwise, can you please remove it from the repository? Thanks!

**Comment by MaddyKapfhammer** [comment]
This directory was used to determine metrics according to the repository (amount of lines, amount of comments etc.) for interest purposes. The directory has now been removed from the repository.
